# Generated by Django 4.2.27 on 2025-12-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('CAD', 'Canadian Dollar (CA$)'), ('GBP', 'British Pound (£)'), ('HTG', 'Haitian Gourde (G)')], max_length=3, unique=True, verbose_name='Code devise')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbole')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, help_text='Taux par rapport à la devise de base (EUR). Ex: 1 EUR = X cette devise', max_digits=12, verbose_name='Taux de change')),
                ('is_default', models.BooleanField(default=False, verbose_name='Devise par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('position', models.CharField(choices=[('before', 'Avant le montant'), ('after', 'Après le montant')], default='after', max_length=10, verbose_name='Position du symbole')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='Décimales')),
                ('thousands_separator', models.CharField(default=' ', max_length=1, verbose_name='Séparateur milliers')),
                ('decimal_separator', models.CharField(default=',', max_length=1, verbose_name='Séparateur décimal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
