# Generated by Django 4.2.27 on 2025-12-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ht', 'Kreyòl Ayisyen'), ('es', 'Español'), ('pt', 'Português'), ('de', 'Deutsch'), ('it', 'Italiano')], max_length=5, unique=True, verbose_name='Code langue')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('native_name', models.CharField(help_text='Ex: Français, English', max_length=50, verbose_name='Nom natif')),
                ('flag_emoji', models.CharField(default='🌐', help_text='Ex: 🇫🇷, 🇬🇧', max_length=10, verbose_name='Emoji drapeau')),
                ('is_default', models.BooleanField(default=False, verbose_name='Langue par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
                'ordering': ['order', '-is_default', 'name'],
            },
        ),
    ]
