# Generated by Django 4.2.27 on 2025-12-05 20:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='N° Facture')),
                ('status', models.CharField(choices=[('draft', '📝 Brouillon'), ('sent', '📧 Envoyée'), ('paid', '✅ Payée'), ('overdue', '⚠️ En retard'), ('cancelled', '❌ Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name="Date d'émission")),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total HT')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total TTC')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Conditions de paiement')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payée le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='N° Commande')),
                ('status', models.CharField(choices=[('pending', '⏳ En attente'), ('confirmed', '✅ Confirmée'), ('processing', '📦 En préparation'), ('shipped', '🚚 Expédiée'), ('delivered', '✔️ Livrée'), ('cancelled', '❌ Annulée'), ('refunded', '💰 Remboursée')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_status', models.CharField(choices=[('pending', '⏳ En attente'), ('paid', '✅ Payée'), ('failed', '❌ Échoué'), ('refunded', '💰 Remboursée')], default='pending', max_length=20, verbose_name='Paiement')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA')),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de port')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Réduction')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('billing_address', models.TextField(blank=True, verbose_name='Adresse de facturation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='N° de suivi')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Expédiée le')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Livrée le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, verbose_name='Produit')),
                ('product_sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total HT')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.invoice')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='invoicing.order', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Entreprise')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('siret', models.CharField(blank=True, max_length=20, verbose_name='SIRET')),
                ('vat_number', models.CharField(blank=True, max_length=30, verbose_name='N° TVA')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil client',
                'verbose_name_plural': 'Profils clients',
            },
        ),
    ]
